### ISSUE TITLE
【演習 2) タスク 2】`uses: ` の末尾にコメントは書けない

### ISSUE THREAD

**Issue by horihiro** [horihiro/containers-cicd-handson-tutorial#15]
コメントも含めて、アクション名として認識されるため、エラーになる。

![image](https://user-images.githubusercontent.com/4566555/187585546-32d35ae7-aadb-4e90-b046-99fceb7043a0.png)

現状:
```
      # Add a step
      - name: Log in to container registry
        uses: docker/login-action@v1 　# 認証処理を行うためのアクション
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
```

改善案:
```
      # Add a step
      - name: Log in to container registry
        # 認証処理を行うためのアクション
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
```
